---
name: Semgrep scan

on:
  pull_request: {}

jobs:
  semgrep:
    name: semgrep-oss/scan
    permissions:
      contents: read
      pull-requests: write
    # If you are self-hosting, change the following `runs-on` value:
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep
    # Skip any PR created by dependabot to avoid permission issues:
    if: (github.actor != 'dependabot[bot]')
    steps:
      - uses: actions/checkout@v4
      - uses: reviewdog/action-setup@v1
      - run: semgrep scan --config https://semgrep-rules.security.agicap.cloud/semgrep_rules.yml --sarif --metrics=off | reviewdog -f=sarif -reporter="github-pr-review"
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
